site_name: Rajtilak Bhattacharjee
site_url: https://www.rajtilak.tech

theme:
  name: material

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Resume: resume/index.md
